[workspace]
resolver = "3"
members = ["crates/http_server"]
default-members = ["crates/http_server"]

[workspace.package]
version = "0.0.1"
authors = ["hxyulin <hxyulin@proton.me>"]
license = "GPLv3"
rust-version = "1.88.0"
edition = "2024"
